### ISSUE TITLE
migrating device code workflow from adal without refresh token

### ISSUE THREAD

**Issue by aldudko** [Azure/azure-sdk-for-go#18679]
Hello,

Kubernetes CLI ([kubectl](https://github.com/kubernetes/kubernetes/blob/release-1.19/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go#L430)) and [Azure/kubelogin](https://github.com/Azure/kubelogin/blob/master/pkg/token/devicecode.go#L38) currently rely on adal's [the device code authentication workflow](https://github.com/Azure/go-autorest/tree/main/autorest/adal#device-code) which allows getting refresh token as a part of [adal.Token](https://pkg.go.dev/github.com/Azure/go-autorest/autorest/adal#Token)
The CLI asks users to go through Azure AD authentication workflow once, and then uses refresh token to renew access token for the next 8? hours without asking users to go through the authentication process once again.

If I understand correctly, in azure-sdk-for-go/sdk/azidentity the access to refresh token was intentionally removed. Since both [NewDeviceCodeCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.1.0#NewDeviceCodeCredential) and [NewInteractiveBrowserCredential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.1.0#NewInteractiveBrowserCredential) workflow provide the access token only, my understanding is that users will have to go through either the interactive workflow or https://microsoft.com/devicelogin hourly. This is certainly not the same workflow users have with adal.

Could you help me to understand what is the intended migration path from `adal` to `azidentity` for such CLIs which doesn't involve redirection users to browser every hour?

**Comment by chlowell** [comment]
Thanks for opening this issue. You understand correctly. `azidentity` credentials return only access tokens, so a CLI that caches these must interactively reauthenticate users as their access tokens expire. The intended migration path is a new user authentication API and persistent caching feature that enables securely storing and accessing authentication data across process executions (#16643). This doesn't exist yet, so I'm afraid at present there's no migration path for this pattern.

How do the tools you mentioned store refresh tokens today?

**Comment by aldudko** [comment]
Thank you for the explanation! I've subscribed to #16643 for updates.

Today `kubectl` keeps everything in a local file in user's home directory (~/.kube/config). For example:
```
...
users:
- name: azure
  user:
    auth-provider:
      config:
        access-token: <token>
        apiserver-id: <server-application-id>
        client-id: <client-application-id>
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "4369"
        expires-on: "1658775533"
        refresh-token: <refresh-token>
        tenant-id: <tenant-id>
      name: azure
```

[`kubelogin'](https://github.com/Azure/kubelogin) uses similar approach with different file location and format.
